[package]
name = "thegraph-core"
description = "Rust core modules for The Graph network"
version = "0.9.3"
repository = "https://github.com/edgeandnode/toolshed"
authors = ["Lorenzo Delgado (LNSD) <lorenzo@edgeandnode.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.81.0"

[features]
default = []
attestation = ["alloy-eip712", "alloy-signers", "alloy-sol-types"]
alloy-contract = ["alloy/contract"]
alloy-eip712 = ["alloy/eip712"]
alloy-full = ["alloy/full"]
alloy-rlp = ["alloy/rlp"]
alloy-signer-local = ["alloy/signer-local"]
alloy-signers = ["alloy/signers"]
alloy-sol-types = ["alloy/sol-types"]
async-graphql = ["dep:async-graphql"]
fake = ["dep:fake"]
serde = ["dep:serde", "dep:serde_with", "alloy/serde"]
signed-message = ["alloy-eip712", "alloy-signers", "alloy-sol-types"]

[dependencies]
alloy = "0.7"
async-graphql = { version = "7.0", optional = true }
bs58 = "0.5"
fake = { version = "3.0", optional = true }
serde = { version = "1.0", optional = true }
serde_with = { version = "3.8", optional = true }
thiserror = "1.0"

[dev-dependencies]
alloy = { version = "0.7", features = ["signer-local"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo_check_external_types]
allowed_external_types = [
    "alloy",
    "alloy::*",
    "alloy_primitives",
    "alloy_primitives::*",
    "alloy_signer",
    "alloy_signer::*",
    "alloy_sol_types",
    "alloy_sol_types::*",
    "async_graphql",
    "async_graphql::*",
    "fake",
    "fake::*",
    "headers",
    "headers::*",
    "headers_core",
    "headers_core::*",
    "serde",
    "serde::*",
]
