[package]
name = "thegraph-core"
description = "A collection of Rust modules shared between The Graph's network services"
version = "0.5.7"
repository = "https://github.com/edgeandnode/toolshed"
authors = ["Lorenzo Delgado (LNSD) <lorenzo@edgeandnode.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.71.1"

[features]
default = ["serde"]
async-graphql-support = ["dep:async-graphql"]
serde = ["dep:serde", "dep:serde_with", "alloy-primitives/serde"]
subgraph-client = [
    "serde",
    "dep:tracing",
    "tracing/attributes",
    "dep:indoc",
    "dep:serde_json",
    "dep:reqwest",
    "dep:thegraph-graphql-http",
    "thegraph-graphql-http/http-client-reqwest",
]

[dependencies]
alloy-primitives = "0.7"
alloy-signer = { version = "0.1", features = ["eip712"] }
alloy-sol-types = "0.7"
async-graphql = { version = "7.0", optional = true }
bs58 = "0.5"
indoc = { version = "2.0.5", optional = true }
reqwest = { version = "0.12", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", features = ["raw_value"], optional = true }
serde_with = { version = "3.8", optional = true }
thegraph-graphql-http = { version = "0.2", optional = true }
thiserror = "1.0"
tracing = { version = "0.1.40", optional = true, default-features = false }
url = "2.5"

[dev-dependencies]
alloy-signer-local = "0.2.0"
assert_matches = "1.5.0"
test-with = { version = "0.13.0", default-features = false }
tokio = { version = "1.37.0", features = ["macros", "rt"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
