[package]
name = "thegraph-core"
description = "A collection of Rust modules shared between The Graph's network services"
version = "0.2.0"
repository = "https://github.com/edgeandnode/toolshed"
authors = ["Lorenzo Delgado (LNSD) <lorenzo@edgeandnode.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.71.1"

[features]
async-graphql-support = ["dep:async-graphql"]
subgraph-client = [
    "dep:tracing",
    "dep:indoc",
    "dep:serde_json",
    "dep:reqwest",
    "dep:thegraph-graphql-http",
    "thegraph-graphql-http/http-client-reqwest",
]

[dependencies]
alloy-primitives = { version = "0.6", features = ["serde"] }
alloy-sol-types = "0.6"
async-graphql = { version = "7.0", optional = true }
bs58 = "0.5"
ethers-core = "2.0.13"
indoc = { version = "2.0.4", optional = true }
lazy_static = "1.4.0"
reqwest = { version = "0.11.24", optional = true }
serde = "1.0"
serde_json = { version = "1.0.114", features = ["raw_value"], optional = true }
serde_with = "3.6"
thegraph-graphql-http = { version = "0.1", optional = true }
thiserror = "1.0"
tracing = { version = "0.1.40", optional = true }
url = "2.5"

[dev-dependencies]
assert_matches = "1.5.0"
test-with = "0.12.5"
tokio = { version = "1.36.0", features = ["macros", "rt"] }
