[package]
name = "thegraph-core"
description = "A collection of Rust modules shared between The Graph's network services"
version = "0.0.1"
edition = "2021"
authors = ["Lorenzo Delgado (LNSD) <lorenzo@edgeandnode.com>"]
license = "MIT"
readme = "README.md"

[features]
async-graphql-support = ["dep:async-graphql"]

[dependencies]
alloy-primitives = { version = "0.6", features = ["serde"] }
alloy-sol-types = "0.6"
async-graphql = { version = "7.0", optional = true }
bs58 = "0.5"
ethers-core = "2.0.13"
lazy_static = "1.4.0"
serde = "1.0"
serde_with = "3.6"
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5.0"
