name: ci
on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Cache rust cargo build files
        uses: Leafwing-Studios/cargo-cache@5edda26afa3d28be5d6ee87d4c69c246e3ee37fb # v1

      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings --force-warn deprecated --force-warn dead-code"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Cache rust cargo build files
        uses: Leafwing-Studios/cargo-cache@5edda26afa3d28be5d6ee87d4c69c246e3ee37fb # v1

      - run: cargo clippy --all --all-targets --all-features

  check-release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings --force-warn deprecated --force-warn dead-code"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache rust cargo build files
        uses: Leafwing-Studios/cargo-cache@5edda26afa3d28be5d6ee87d4c69c246e3ee37fb # v1

      - name: check (release)
        run: cargo check --release --all --all-targets --all-features

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings --force-warn deprecated --force-warn dead-code"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache rust cargo build files
        uses: Leafwing-Studios/cargo-cache@5edda26afa3d28be5d6ee87d4c69c246e3ee37fb # v1

      - name: Unit tests
        run: cargo test --verbose --workspace --all-features --lib -- --nocapture

      - name: Integration tests
        run: cargo test --verbose --workspace --all-features --tests '*' -- --nocapture

  # Check semver compatibility (on pull requests only)
  semver:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [rustfmt, clippy, check-release, tests]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install cargo-semver-checks
        uses: baptiste0928/cargo-install@1cd874a5478fdca35d868ccc74640c5aabbb8f1b # v3
        with:
          crate: cargo-semver-checks

      - name: Check semver
        run: cargo semver-checks --baseline-rev=${{ github.event.pull_request.base.sha }} --verbose

