name: ci
on:
  pull_request:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Cache rust cargo build files
        uses: Leafwing-Studios/cargo-cache@v1
        with:
          cache-group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Cache rust cargo build files
        uses: Leafwing-Studios/cargo-cache@v1
        with:
          cache-group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

      - run: cargo clippy --all --all-targets --all-features

  release-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache rust cargo build files
        uses: Leafwing-Studios/cargo-cache@v1
        with:
          cache-group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

      - name: check (release)
        run: cargo check --release --all --all-targets --all-features

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache rust cargo build files
        uses: Leafwing-Studios/cargo-cache@v1
        with:
          cache-group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

      - name: Unit tests
        run: cargo test --verbose --workspace --lib -- --nocapture

      - name: Integration tests
        run: cargo test --verbose --workspace --tests '*' -- --nocapture
